# SPDX-License-Identifier: GPL-2.0
ARG BASE
# ------------------------------------------------------------------------------
FROM $BASE as base

# common builder and runtime dependencies
# explicit MetaSTAAR dependencies, see:
#    https://github.com/xihaoli/MetaSTAAR/blob/main/README.md
# [MetaSTAAR links to R packages]
# Rcpp, RcppArmadillo and STAAR
# [and also imports R packages]
# Rcpp, STAAR, Matrix, dplyr, expm, MASS

RUN apt -y update -qq && DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		gfortran \
		libboost-filesystem1.83.0 \
		libboost-regex1.83.0-icu74 \
		liblapack3 \
		libblas3 \
		libeigen3-dev \
		libbz2-1.0 \
		libdeflate0 \
		libicu74 \
		libkf5i18n5 \
		liblzma5 \
		libuv1 \
		libzstd1 \
		zlib1g \
		r-cran-bit \
		r-cran-bit64 \
		r-cran-bitops \
		r-cran-blob \
		r-cran-boot \
		r-cran-brio \
		r-cran-data.table \
		r-cran-dbi \
		r-cran-dplyr \
		r-cran-expm \
		r-cran-forcats \
		r-cran-foreach \
		r-cran-formatr \
		r-cran-futile.logger \
		r-cran-futile.options \
		r-cran-genetics \
		r-cran-glmnet \
		r-cran-igraph \
		r-cran-iterators \
		r-cran-jomo \
		r-cran-lambda.r \
		r-cran-lattice \
		r-cran-lifecycle \
		r-cran-lmtest \
		r-cran-knitr \
		r-cran-mass \
		r-cran-matrix \
		r-cran-matrixmodels \
		r-cran-memoise \
		r-cran-mice \
		r-cran-minqa \
		r-cran-mitml \
		r-cran-mgcv \
		r-cran-nloptr \
		r-cran-nnet \
		r-cran-numderiv \
		r-cran-optparse \
		r-cran-ordinal \
		r-cran-pan \
		r-cran-pillar \
		r-cran-plogr \
		r-cran-progress \
		r-cran-purrr \
		r-cran-quantreg \
		r-cran-qqman \
		r-cran-quantreg \
		r-cran-rcurl \
		r-cran-readr \
		r-cran-reshape2 \
		r-cran-rlang \
		r-cran-rpart \
		r-cran-rsqlite \
		r-cran-r.utils \
		r-cran-sandwich \
		r-cran-shape \
		r-cran-snow \
		r-cran-sparsem \
		r-cran-stringr \
		r-cran-survival \
		r-cran-testthat \
		r-cran-tidyr \
		r-cran-tidyverse \
		r-cran-tibble \
		r-cran-tzdb \
		r-cran-ucminf \
		r-cran-vctrs \
		r-cran-vroom \
		r-cran-withr \
		r-cran-zoo \
		r-cran-biocmanager \
		r-bioc-biocversion \
		r-bioc-biobase \
		r-bioc-biocgenerics \
		r-bioc-biocparallel \
		r-bioc-biostrings \
		r-bioc-dnacopy \
		r-bioc-genomeinfodbdata \
		r-bioc-genomeinfodb \
		r-bioc-genomicranges \
		r-bioc-iranges \
		r-bioc-rbgl \
		r-bioc-s4vectors \
		r-bioc-snpstats \
		r-bioc-xvector \
		r-bioc-zlibbioc \
		r-cran-fansi \
	&& \
	apt -y clean && rm -rf /var/lib/apt/lists/* /tmp/*

# ------------------------------------------------------------------------------
# BUILDER LAYER
FROM base as builder

RUN apt -y update -qq && DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		libboost-filesystem1.83-dev \
		libboost-regex1.83-dev \
		liblapack-dev \
		libblas-dev \
		libbz2-dev \
		libdeflate-dev \
		libkf5i18n-dev \
		liblzma-dev \
		libuv1-dev \
		libzstd-dev \
		zlib1g-dev \
		autoconf \
		automake \
		build-essential \
		cmake \
		gcc \
		git \
		make \
		pkg-config \
		r-cran-codetools \
		r-cran-rcpp \
		r-cran-rcpparmadillo \
		r-cran-rcppeigen \
		r-cran-remotes

WORKDIR /usr/src

# release-74-2 tag
RUN git clone -b release-74-2 --single-branch --depth=1 \
		https://github.com/unicode-org/icu && cd icu/icu4c/source && \
	./runConfigureICU Linux/clang && make install

RUN \
	Rscript -e 'install.packages(c("backports"))' && \
	Rscript -e 'install.packages(c("withr"))' && \
	Rscript -e 'install.packages(c("fansi"))' && \
	Rscript -e 'install.packages(c("stringi"))' && \
	Rscript -e 'install.packages(c("tidyselect"))' && \
	Rscript -e 'install.packages(c("broom"))' && \
	Rscript -e 'install.packages(c("processx"))' && \
	Rscript -e 'install.packages(c("callr"))' && \
	Rscript -e 'install.packages(c("data.table"))' && \
	Rscript -e 'install.packages(c("cli"))' && \
	Rscript -e 'install.packages(c("logistf"))' && \
	Rscript -e 'install.packages(c("formula.tools"))' && \
	Rscript -e 'install.packages(c("operator.tools"))' && \
	Rscript -e 'install.packages(c("lme4"))' && \
	Rscript -e 'install.packages(c("dplyr"))' && \
	Rscript -e 'install.packages(c("jomo"))' && \
	Rscript -e 'install.packages(c("mitml"))' && \
	Rscript -e 'install.packages(c("mice"))' && \
	Rscript -e 'install.packages(c("pkgbuild"))'

RUN	Rscript -e 'BiocManager::install(c("GWASExactHW"))' && \
	Rscript -e 'BiocManager::install(c("gdsfmt"))' && \
	Rscript -e 'BiocManager::install(c("GWASTools"))' && \
	Rscript -e 'BiocManager::install(c("quantsmooth"))' && \
	Rscript -e 'BiocManager::install(c("SeqArray"))' && \
	Rscript -e 'BiocManager::install(c("SeqVarTools"))' && \
	Rscript -e 'BiocManager::install(c("SNPRelate"))' && \
	Rscript -e 'BiocManager::install("GENESIS")'

RUN \
	Rscript -e 'remotes::install_github("hihg-um/GMMAT")' && \
	Rscript -e 'remotes::install_github("hihg-um/STAAR")' && \
	Rscript -e 'remotes::install_github("hihg-um/MultiSTAAR")' && \
	Rscript -e 'remotes::install_github("hihg-um/MetaSTAAR")'

# RUNTIME LAYER
FROM base

ARG BASE
ARG RUN_CMD
ARG BUILD_REPO
ARG BUILD_TIME

COPY --from=builder /usr/local/lib/R /usr/local/lib/R
COPY --chmod=0555 src/test/${RUN_CMD}.sh /test.sh
COPY --chmod=0555 src/test/${RUN_CMD}.R /

ENTRYPOINT [ "Rscript" ]

LABEL org.opencontainers.image.base.digest=""
LABEL org.opencontainers.image.base.name="${BASE}"
LABEL org.opencontainers.image.created="${BUILD_TIME}"
LABEL org.opencontainers.image.description="STAAR R library and dependencies"
LABEL org.opencontainers.image.title="HIHG: ${RUN_CMD}"
LABEL org.opencontainers.image.url="${BUILD_REPO}"
# ------------------------------------------------------------------------------
