# SPDX-License-Identifier: GPL-2.0
ARG BASE_IMAGE
FROM $BASE_IMAGE as builder

ARG RUNCMD

# install all possible R dependencies from pre-packaged ubuntu binaries
# - much faster install than 'install.packages()' inside R
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    cmake \
    git \
    libblas-dev \
    libstatgen-dev \
    libsuperlu-dev \
    libzmat-dev \
    libzzip-dev \
    libzstd-dev \
    zlib1g-dev \
    python3 \
    python3-pip \
    python3-pymatgen \
    python3-venv \
    python3-wheel \
    r-cran-biocmanager \
    r-bioc-biocversion \
    r-cran-devtools \
    r-cran-optparse \
    r-cran-qlcmatrix \
    r-cran-r.utils \
    r-cran-rcpp \
    r-cran-rcppparallel \
    r-cran-roxygen2 \
    r-cran-rversions

# pick up remaining bioconductor dependencies not packaged w/ ubuntu 
RUN Rscript -e 'BiocManager::install("SPAtest")' && \
    Rscript -e 'BiocManager::install("RhpcBLASctl")' && \
    Rscript -e 'BiocManager::install("SKAT")' && \
    Rscript -e 'BiocManager::install("MetaSKAT")'

# in Ubuntu 23.04 and later, an error is now passed for attempting to
# globally install packages with an external package manager like pip.
# to solve: use virtual environments for package installs
ENV VIRTUAL_ENV=/opt/python/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH=$PATH:"$VIRTUAL_ENV/opt/python//pythocTH"
RUN pip install click cget savy six

RUN git clone https://github.com/saigegit/SAIGE

# Force step_2 to use 1 single thread. More threads are ineffective
ENV OMP_NUM_THREADS=1
RUN R CMD INSTALL SAIGE

FROM $BASE_IMAGE
 
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# install all possible R dependencies from pre-packaged ubuntu binaries
# - much faster install than 'install.packages()' inside R
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    r-cran-biocmanager \
    r-bioc-biocversion \
    r-cran-optparse \
    r-cran-qlcmatrix \
    r-cran-r.utils

# pick up remaining bioconductor dependencies not packaged w/ ubuntu 
WORKDIR /app

COPY --from=builder /SAIGE/extdata/*.R /usr/local/bin/
RUN chmod ug+x /usr/local/bin/*.R

COPY --from=builder /usr/local/lib/R /usr/local/lib/
