# SPDX-License-Identifier: GPL-2.0
ARG BASE
# ------------------------------------------------------------------------------
# BASE LAYER
FROM $BASE as base

# shared builder and runtime dependencies
RUN apt -y update -qq && DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		libbz2-1.0 \
		libdeflate0 \
		libeigen3-dev \
		liblzma5 \
		libzstd1 \
		zlib1g \
		xzip \
		r-cran-backports \
		r-cran-bit \
		r-cran-bit64 \
		r-cran-broom \
		r-cran-crayon \
		r-cran-data.table \
		r-cran-domc \
		r-cran-dplyr \
		r-cran-forcats \
		r-cran-foreach \
		r-cran-generics \
		r-cran-generics \
		r-cran-glmnet \
		r-cran-haven \
		r-cran-hms \
		r-cran-iterators \
		r-cran-mice \
		r-cran-jomo \
		r-cran-lattice \
		r-cran-jomo \
		r-cran-lattice \
		r-cran-lme4 \
		r-cran-matrix \
		r-cran-mice \
		r-cran-minqa \
		r-cran-mitml \
		r-cran-nloptr \
		r-cran-numderiv \
		r-cran-ordinal \
		r-cran-pan \
		r-cran-progress \
		r-cran-readr \
		r-cran-shape \
		r-cran-stringi \
		r-cran-stringr \
		r-cran-tidyr \
		r-cran-ucminf \
		r-cran-vroom \
		r-cran-tzdb \
		r-bioc-biobase \
		r-bioc-biocgenerics \
		r-bioc-biocparallel \
		r-bioc-biocversion \
		r-bioc-biostrings \
		r-bioc-genomeinfodb \
		r-bioc-genomicranges \
		r-bioc-s4vectors \
		r-bioc-iranges \
		r-bioc-zlibbioc \
	&& \
	apt -y clean && rm -rf /var/lib/apt/lists/* /tmp/*

# ------------------------------------------------------------------------------
# BUILDER LAYER
FROM base as builder

# builder only dependencies
RUN apt -y update -qq && DEBIAN_FRONTEND=noninteractive apt -y install \
	--no-install-recommends --no-install-suggests \
		libbz2-dev \
		libdeflate-dev \
		liblzma-dev \
		libzstd-dev \
		zlib1g-dev \
		autoconf \
		automake \
		cmake \
		g++ \
		make \
		r-base-dev \
		r-cran-codetools \
		r-cran-rcpp \
		r-cran-rcpparmadillo \
		r-cran-rcppeigen \
		r-cran-remotes \
		r-cran-testthat \
		r-cran-biocmanager

# install GMMAT
RUN \
	Rscript -e 'install.packages(c("CompQuadForm"))' && \
	Rscript -e 'install.packages(c("operator.tools"))' && \
	Rscript -e 'install.packages(c("formula.tools"))' && \
	Rscript -e 'install.packages(c("GWASExactHW"))' && \
	Rscript -e 'install.packages(c("logistf"))' && \
	Rscript -e 'install.packages(c("RcppArmadillo"))' && \
	Rscript -e 'install.packages(c("data.table"))' && \
	Rscript -e 'BiocManager::install(c("GWASExactHW"))' && \
	Rscript -e 'BiocManager::install(c("gdsfmt"))' && \
	Rscript -e 'BiocManager::install(c("SeqArray"))' && \
	Rscript -e 'BiocManager::install(c("SeqVarTools"))' && \
	Rscript -e 'remotes::install_github("hihg-um/GMMAT@1272b9f9306406e07d84ae748811cb755c3b9abe")'

# ------------------------------------------------------------------------------
# RUNTIME LAYER
FROM base

# build-args
ARG BASE
ARG RUN_CMD
ARG BUILD_REPO
ARG BUILD_TIME

COPY --from=builder /usr/local/lib/R /usr/local/lib/R
COPY --chmod=0555 src/test/${RUN_CMD}.sh /test.sh

# Old packages:
#  'backports', 'brio', 'broom', 'callr', 'cli', 'crayon', 'data.table',
#  'digest', 'evaluate', 'fansi', 'fs', 'littler', 'lme4', 'minqa', 'nloptr',
#  'pkgbuild', 'processx', 'remotes', 'rlang', 'shape', 'stringi', 'testthat',
#  'tidyselect', 'withr', 'zlibbioc', 'KernSmooth', 'lattice',
#  'nlme', 'survival'

ENTRYPOINT [ "Rscript" ]

LABEL org.opencontainers.image.base.digest=""
LABEL org.opencontainers.image.base.name="${BASE}"
LABEL org.opencontainers.image.created="${BUILD_TIME}"
LABEL org.opencontainers.image.description="GMMAT R library and dependencies"
LABEL org.opencontainers.image.title="HIHG: ${RUN_CMD}"
LABEL org.opencontainers.image.url="${BUILD_REPO}"
# ------------------------------------------------------------------------------
