# SPDX-License-Identifier: GPL-2.0
ARG BASE_IMAGE
FROM $BASE_IMAGE as builder

ARG RUNCMD

RUN DEBIAN_FRONTEND=noninteractive \
	apt -y install git

RUN git clone https://github.com/hihg-um/mergeomics.git

FROM $BASE_IMAGE
WORKDIR /app

COPY --from=builder mergeomics/*.R /src/
